import {
  Avatar1,
  Avatar2,
  Avatar3,
  Avatar4,
  Avatar5,
  Avatar6,
  Avatar7,
  Avatar8,
} from 'data/images';

export const rows = [
  {
    id: 1,
    courses: 'Designing Landing Page',
    members: [Avatar6, Avatar8, Avatar2],
    progress: 60,
    status: 'in progress',
    timeLeft: '2 Days',
  },
  {
    id: 2,
    courses: 'Setting Up Analytics',
    members: [Avatar1, Avatar7, Avatar3, Avatar8],
    progress: 100,
    status: 'completed',
    timeLeft: '3 Hours',
  },
  {
    id: 3,
    courses: 'Fixing Critical Bugs',
    members: [Avatar2, Avatar5, Avatar8, Avatar4, Avatar7, Avatar1],
    progress: 100,
    status: 'completed',
    timeLeft: '5 Hours',
  },
  {
    id: 4,
    courses: 'Creating Wireframes',
    members: [Avatar8, Avatar3, Avatar5],
    progress: 75,
    status: 'in progress',
    timeLeft: '4 Days',
  },
  {
    id: 5,
    courses: 'Fixing UI/UX Issues',
    members: [Avatar7, Avatar4, Avatar1, Avatar5, Avatar2],
    progress: 0,
    status: 'pending',
    timeLeft: '5 Days',
  },
  {
    id: 6,
    courses: 'Writing Unit Tests',
    members: [Avatar4, Avatar6, Avatar1, Avatar5],
    progress: 40,
    status: 'in progress',
    timeLeft: '3 Days',
  },
  {
    id: 7,
    courses: 'Conducting User Testing',
    members: [Avatar5, Avatar2, Avatar7, Avatar3, Avatar1],
    progress: 100,
    status: 'completed',
    timeLeft: '4 Hours',
  },
  {
    id: 8,
    courses: 'Planning Product Launch',
    members: [Avatar3, Avatar1, Avatar6],
    progress: 55,
    status: 'in progress',
    timeLeft: '4 Days',
  },
  {
    id: 9,
    courses: 'Updating Website Content',
    members: [Avatar2, Avatar1, Avatar4, Avatar8],
    progress: 100,
    status: 'completed',
    timeLeft: '2 Hours',
  },
  {
    id: 10,
    courses: 'Deploying Application',
    members: [Avatar5, Avatar2],
    progress: 0,
    status: 'pending',
    timeLeft: '7 Days',
  },
];
